// Generated by jextract

package jp.yukoba.ale;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ale_cloneState",
        constants$10.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ale_restoreState",
        constants$2.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ale_cloneSystemState",
        constants$10.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ale_restoreSystemState",
        constants$2.const$3
    );
}


