// Generated by jextract

package jp.yukoba.ale;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ale_getAvailableDifficulties",
        constants$6.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ale_setDifficulty",
        constants$6.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ale_getDifficulty",
        constants$6.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ale_getLegalActionSet",
        constants$6.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ale_getMinimalActionSet",
        constants$6.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ale_getFrameNumber",
        constants$6.const$5
    );
}


