// Generated by jextract

package jp.yukoba.ale;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ale_lives",
        constants$6.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ale_getEpisodeFrameNumber",
        constants$6.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "ale_getScreenWidth",
        constants$6.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ale_getScreenHeight",
        constants$6.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ale_getScreenGrayscale",
        constants$6.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ale_getScreenRGB",
        constants$6.const$1
    );
}


